application/aboutus/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.MemberListView.as_view(), name='all'),
    path('<int:pk>/', views.MemberDetailView.as_view(), name='detail'),
]

application/aboutus/aboutus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/aboutus/about/models.py
from django.db import models

from django.db import models

# Create your models here.
# name, role, description, pronouns, image, meetingSchedule, teamComms

class Member(models.Model):
    name = models.CharField(max_length=200, null=False)
    role = models.CharField(max_length=200, null=False)
    description = models.CharField(max_length=500)
    pronouns = models.CharField(max_length=100, null=False)
    image = models.ImageField(upload_to='member_images')

    def __str__(self):
        return self.name

application/aboutus/about/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .models import Member
from django.urls import reverse_lazy


class MemberListView(generic.ListView):
    model = Member
    success_url = reverse_lazy("index")
    context_object_name = 'member_list'
    template_name = 'about/index.html'

    def get_queryset(self):
        return Member.objects.all()

    
def detail(request, pk):
    member = get_object_or_404(Member, pk=pk)
    return render(request, 'about/detail.html')

class MemberDetailView(generic.DetailView):
    model = Member
    template_name = 'about/detail.html'

application/aboutus/about/templates/about/detail.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Member Detail{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    </head>
    <body>
        <div class="container">
            <h2 class="center-align">{{ member.name }}</h2>
            <div class="row">
                <div class="col s12 m6 l4">
                    <div class="card hoverable">
                        <div class="card-image">
                            {% if member.image %}
                                <img src="{{ member.image.url }}" alt="{{ member.name }}" class="responsive-img">
                            {% else %}
                                <img src="{% static '../../media/member_images/grumpmonkey.jpeg' %}" alt="default avatar" class="responsive-img">
                            {% endif %}
                        </div>
                        <div class="card-content">
                            <h4 class="card-title center-align">{{ member.name }}</h4>
                            <p class="center-align"><strong>{{ member.role }}</strong></p>
                            <p class="center-align">{{ member.pronouns }}</p>
                            <p class="center-align">{{ member.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>

application/aboutus/about/templates/about/index.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Members{% endblock %}</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    </head>
    <body>
        <div class="container">
            <h2 class="center-align">All Members</h2>
	    <p class="center-align"><strong>Meeting Weds in class and Saturday 8am</strong></p>
            <p class="center-align"><strong>Team communication: Discord (https://discord.gg/tzZ3p8sq)</strong></p>
            <div class="row">
                {% for member in member_list %}
                <div class="col s12 m6 l4">
                    <div class="card hoverable">
                        <div class="card-image">
                            {% if member.image %}
                                <img src="{{ member.image.url }}" alt="{{ member.name }}" class="responsive-img">
                            {% else %}
                                <img src="{% static '../../media/member_images/grumpmonkey.jpeg' %}" alt="default avatar" class="responsive-img">
                            {% endif %}
                        </div>
                        <div class="card-content">
                            <h4 class="card-title center-align">{{ member.name }}</h4>
                            <p class="center-align"><strong>{{ member.role }}</strong></p>
                            <p class="center-align">{{ member.pronouns }}</p>
                            <p class="center-align">{{ member.description }}</p>
                        </div>
                        <div class="card-action center-align">
                            <a href="{% url 'about:detail' member.id %}" class="waves-effect waves-light btn">Click me to learn more about me</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>